# see https://doc.rust-lang.org/cargo/reference/manifest.html

# How to seort dependencies.
sort_dependencies = ["alphabetical", "lenght"]

format_toml = true

toml-sections-order = [
    "package",    
    "lib",
    "bins",
    "example",
    "test",
    "bench",
    "dependencies",
    "dev-dependencies",
    "build-dependencies",
    "target",
    "badges",
    "features",
    "patch",
    "replace",
    "profile",
    "workspace",
    "cargo-features"
]

package-order = [
    { description="0"},
    { version="1"},
    { edition="2"},
]

# Defines the order of the package entries.
package-order = [
    "name", # The name of the package.
    "version", # The version of the package.
    "authors", # The authors of the package.
    "edition", # The Rust edition.
    "rust-version", # The minimal supported Rust version.
    "description", # A description of the package.
    "documentation", # URL of the package documentation.
    "readme", # Path to the package's README file.
    "homepage", # URL of the package homepage.
    "repository", # URL of the package source repository.
    "license", # The package license.
    "license-file", # Path to the text of the license.
    "keywords", # Keywords for the package.
    "categories", # Categories of the package.
    "workspace", # Path to the workspace for the package.
    "build", # Path to the package build script.
    "links", # Name of the native library the package links with.
    "exclude", # Files to exclude when publishing.
    "include", # Files to include when publishing.
    "publish", # Can be used to prevent publishing the package.
    "metadata", # Extra settings for external tools.
    "default-run", # The default binary to run by cargo run.
    "autobins", # Disables binary auto discovery.
    "autoexamples", # Disables example auto discovery.
    "autotests", # Disables test auto discovery.
    "autobenches", # Disables bench auto discovery.
    "resolver", # Sets the dependency resolver to use.
]