[package]
name = "cargo-verify"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml_edit = "0.14.4" 
cargo-fmt={path="../cargo-fmt"}
